var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/learn/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__089q8m7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1475dxi.js")
R.c("server/chunks/ssr/node_modules_next_dist_0bw_x_7._.js")
R.c("server/chunks/ssr/_0q230s_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1ypm6fc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0h6m_6o._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/_0xaw5ip._.js")
R.c("server/chunks/ssr/app_error_tsx_1zds1ns._.js")
R.c("server/chunks/ssr/app_not-found_tsx_1gi3i27._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_learn_[slug]_page_actions_16qe_et.js")
R.m(88511)
module.exports=R.m(88511).exports
