// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/auth/callback" | "/book-consultation" | "/calculator" | "/contact" | "/dashboard" | "/forgot-password" | "/funds" | "/funds/[schemeCode]" | "/get-started" | "/learn" | "/learn/[slug]" | "/login" | "/onboarding" | "/portfolio" | "/reset-password" | "/signup" | "/stocks"
type AppRouteHandlerRoutes = "/api/funds" | "/api/market-indices" | "/api/market-news" | "/api/mutual-funds/search" | "/api/stocks/history" | "/api/stocks/market" | "/api/stocks/overview" | "/api/stocks/search" | "/favicon.ico" | "/sitemap.xml"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/api/funds": {}
  "/api/market-indices": {}
  "/api/market-news": {}
  "/api/mutual-funds/search": {}
  "/api/stocks/history": {}
  "/api/stocks/market": {}
  "/api/stocks/overview": {}
  "/api/stocks/search": {}
  "/auth/callback": {}
  "/book-consultation": {}
  "/calculator": {}
  "/contact": {}
  "/dashboard": {}
  "/favicon.ico": {}
  "/forgot-password": {}
  "/funds": {}
  "/funds/[schemeCode]": { "schemeCode": string; }
  "/get-started": {}
  "/learn": {}
  "/learn/[slug]": { "slug": string; }
  "/login": {}
  "/onboarding": {}
  "/portfolio": {}
  "/reset-password": {}
  "/signup": {}
  "/sitemap.xml": {}
  "/stocks": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
